<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.933" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2018-08-13T21:02:59" tests="0" failures="0" time="0">
  </testsuite>
  <testsuite name="Registration Page" timestamp="2018-08-13T21:02:59" tests="1" file="C:\Users\Catania\Desktop\daniela_test\RegistrationPage_test.js" failures="1" time="0.933">
    <testcase name="Registration Page: Test Registration Page - Check for Field Validations" time="0.933" classname="Test Registration Page - Check for Field Validations">
      <failure message="expected web page to include &quot;The form hasn&apos;t been completed properly. Please look again at the boxes marked as incorrect in the form.&quot;" type="Error"><![CDATA[expected web page to include "The form hasn't been completed properly. Please look again at the boxes marked as incorrect in the form."

Scenario Steps:

- I.see("The form hasn't been completed properly. Please look again at the boxes marked as incorrect in the form.") at Object.obj.(anonymous function).obj.(anonymous function) [as see] (C:\Users\Catania\AppData\Roaming\npm\node_modules\codeceptjs\lib\actor.js:28:26)

]]></failure>
    </testcase>
  </testsuite>
</testsuites>